name: Test

on:

  push:
    branches:
    - '**'
    paths:
    - '**.py'
    - '**.yaml'

jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
        
      - name: Install dependencies
        run: pip3 install pytest

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Pytest
        run: |
          COVERAGE=`python3 -m pytest --cov=amersham ./test/ | \
            grep -oE "[0-9]+%" | \
            tail -1 | \
            sed 's/.$//'1`
          
          if (( $COVERAGE >= 95 )); then
            COLOR=brightgreen
          elif (( $COVERAGE >= 90 )); then
            COLOR=green
          elif (( $COVERAGE >= 80 )); then
            COLOR=yellowgreen
          elif (( $COVERAGE >= 70 )); then
            COLOR=yellow
          elif (( $COVERAGE >= 60 )); then
            COLOR=orange
          else
            COLOR=red
          fi

          echo "::set-env name=COVERAGE::$COVERAGE"
          echo "::set-env name=COLOR::$COLOR"

          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          echo "COLOR=$COLOR" >> $GITHUB_ENV

      - name: Generate coverage badge
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a15864cab2eed694c754703ad4b73181
          filename: amersham-coverage-badge.json
          label: coverage
          message: ${{ env.COVERAGE }}%
          color: ${{ env.COLOR }}
          style: flat
          namedLogo: github